### PR TITLE
GH-45 Backport Paper 1.13.2 Async Chunk Generation (and Loading) (Resolves #45)

### LINKED ISSUE #45: Parallel Chunk Generation
https://github.com/TitanVale/Titanium/pull/12

### PR DESCRIPTION
**Pull request by P3ridot**
#45 

Finally after lots of tries I achieved Async Chunk Generation (1 thread per world) by backporting Paper 1.13.2 Async Chunk System (thanks for idea @LewUwU). When I will be sure everything works fine I will merge this to `dev`.

Titanium with this patch can be obtained from [Jenkins](https://jenkins.titanvale.net/job/Titanium/job/async-chunks-gen/)

### CODE REVIEW

**Comment by LewUwU** [comment]
After testing a bit in production, everything seems to work fine

**Comment by LewUwU** [comment]
@P3ridot 
[14:07:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Already decorating
	at net.minecraft.server.v1_8_R3.BiomeDecorator.a(SourceFile:25)
	at net.minecraft.server.v1_8_R3.BiomeBase.a(BiomeBase.java:343)
	at net.minecraft.server.v1_8_R3.ChunkProviderGenerate.getChunkAt(ChunkProviderGenerate.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.generator.NormalChunkGenerator.getChunkAt(NormalChunkGenerator.java:51)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:431)
	at net.minecraft.server.v1_8_R3.Chunk.loadNearby(Chunk.java:1376)
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.postChunk(ChunkProviderServer.java:337)
	at net.minecraft.server.v1_8_R3.PaperAsyncChunkProvider$PendingChunk.postChunk(PaperAsyncChunkProvider.java:513)
	at net.minecraft.server.v1_8_R3.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:98)
	at net.minecraft.server.v1_8_R3.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:91)
	at net.minecraft.server.v1_8_R3.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:86)
	at net.minecraft.server.v1_8_R3.PaperAsyncChunkProvider.processMainThreadQueue(PaperAsyncChunkProvider.java:79)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:1074)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:308)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:1040)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:852)
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:134)
	at java.lang.Thread.run(Thread.java:829) ~[?:?]

Can be reproduced some times by creating a world with Multiverse-Core (/mv create worldname normal)

**Comment by P3ridot** [comment]
[This patch](https://github.com/TitaniumMC/Titanium/blob/main/patches/server/0030-Implement-Migot-0027-Enable-Concurrent-Chunk-Decorat.patch) should fix this, because that exception just don't appear in any other situation. And from my small investigation Multiverse-Core don't do anything with BiomeDecorator or something.

**Comment by LewUwU** [comment]
> > [This patch](https://github.com/TitaniumMC/Titanium/blob/main/patches/server/0030-Implement-Migot-0027-Enable-Concurrent-Chunk-Decorat.patch) should fix this - that exception just can't appear in any other situation. Also from my small investigation Multiverse-Core don't do anything with BiomeDecorator or something.
> 
> So @LewUwU are you using Titanium or just this patch? If second option check the result when you use patch mentioned above

Just this patch, i fixed it by allowing concurrently access to the BiomeDecorator but your option should fix some unknown bugs

**Comment by P3ridot** [comment]
> > > [This patch](https://github.com/TitaniumMC/Titanium/blob/main/patches/server/0030-Implement-Migot-0027-Enable-Concurrent-Chunk-Decorat.patch) should fix this - that exception just can't appear in any other situation. Also from my small investigation Multiverse-Core don't do anything with BiomeDecorator or something.
> > 
> > 
> > So @LewUwU are you using Titanium or just this patch? If second option check the result when you use patch mentioned above
> 
> Just this patch, i fixed it by allowing concurrently access to the BiomeDecorator but your option should fix some unknown bugs

Okay, so if everything will work I will merge this PR in a few days

**Comment by LewUwU** [comment]
After viewing some Spark profilers with this patch, there's only lag spikes in Chunk#loadNearby (up to 1k ms), i will see what can be done to optimise that method

**Comment by P3ridot** [comment]
> After viewing some Spark profilers with this patch, there's only lag spikes in Chunk#loadNearby (up to 1k ms), i will see what can be done to optimise that method

After looking a little in code there is no much calculations - probably chunks are loaded synchronously, but I have to make sure

**Comment by LewUwU** [comment]
> > After viewing some Spark profilers with this patch, there's only lag spikes in Chunk#loadNearby (up to 1k ms), i will see what can be done to optimise that method
> 
> After looking a little in code there is no much calculations - probably chunks are loaded synchronously, but I have to make sure

AFAIK there's also chunk population in that method

**Comment by P3ridot** [comment]
> AFAIK there's chunk population in that method (Also we should change the isChunkLoaded to getChunkIfLoaded)

Oh, yeah. And why getChunkIfLoaded? I don't get the reason why 🤔

**Comment by LewUwU** [comment]
> > AFAIK there's chunk population in that method (Also we should change the isChunkLoaded to getChunkIfLoaded)
> 
> Oh, yeah. And why getChunkIfLoaded? I don't get the reason why 🤔

isChunkLoaded -> getChunkAt can be replaced by getChunkIfLoaded

**Comment by P3ridot** [comment]
> > > AFAIK there's chunk population in that method (Also we should change the isChunkLoaded to getChunkIfLoaded)
> > 
> > 
> > Oh, yeah. And why getChunkIfLoaded? I don't get the reason why 🤔
> 
> isChunkLoaded -> getChunkAt can be replaced by getChunkIfLoaded
Right, I did that and everything looks fine - but despite that it's still have to be optimized even more

**Comment by P3ridot** [comment]
I have no idea how we could optimise this even more - we would probably have to optimise decorating (so generating trees etc.) or find a way to do that asynchronously

**Comment by LewUwU** [comment]
> I have no idea how we could optimise this even more - we would probably have to optimise decorating (so generating trees etc.) or find a way to do that asynchronously

The generators should be recoded to support async gen too, some biomes decoration got buggy after being generated (water lily in the air and etc)

**Comment by P3ridot** [comment]
> > I have no idea how we could optimise this even more - we would probably have to optimise decorating (so generating trees etc.) or find a way to do that asynchronously
> 
> The generators should be recoded to support async gen too, some biomes decoration got buggy after being generated (water lily in the air and etc)

I know it should, but it wouldn't be easy. But I looked deeper in the spark and it looks sometimes even 50% are used by ore generation. So maybe there I'll try to optimise it.

**Comment by P3ridot** [comment]
I'll try to add some micro optimizations, but currently I don't have idea how to optimize it more. Then I will merge this PR and optimize terrain decoration in the future. Probably we didn't saved much performance, but maybe a little by offloading terrain generation...

**Comment by P3ridot** [comment]
So I'll optimized chunks decoration (probably a little, but still). Now we have to pray that everything still works (mostly ore generation).

And like I said, I will merge this branch soon. We actually saved much performance - server couldn't have stable 20 TPS when terrain generation was sync. 

Optimizing chunks decoration would be great, but unfortunately I don't have much time to think how actually do that. In best scenario I would somehow do that asynchronously, but we have to think realisticly...

**Comment by P3ridot** [comment]
To the moon! 🌕✨

**Pull request merged**
